OGRE: Ogre::PageContentCollectionFactory Class Reference
Ogre::PageContentCollectionFactory Class Reference abstract
Optional Components » Paging
Define the interface to a factory class that will create subclasses of PageContentCollection.
#include <OgrePageContentCollectionFactory.h>
Public Member Functions
PageContentCollectionFactory ()
virtual ~PageContentCollectionFactory ()
virtual PageContentCollection * createInstance ()=0
virtual void destroyInstance (PageContentCollection *)=0
virtual const String & getName () const =0
Detailed Description
Define the interface to a factory class that will create subclasses of PageContentCollection.
Constructor & Destructor Documentation
Ogre::PageContentCollectionFactory::PageContentCollectionFactory () inline
virtual Ogre::PageContentCollectionFactory::~PageContentCollectionFactory () inline virtual
References createInstance(), destroyInstance(), and getName().
Member Function Documentation
virtual const String& Ogre::PageContentCollectionFactory::getName () const pure virtual
Implemented in Ogre::SimplePageContentCollectionFactory.
Referenced by ~PageContentCollectionFactory().
virtual PageContentCollection* Ogre::PageContentCollectionFactory::createInstance () pure virtual
Implemented in Ogre::SimplePageContentCollectionFactory.
Referenced by ~PageContentCollectionFactory().
virtual void Ogre::PageContentCollectionFactory::destroyInstance (PageContentCollection *) pure virtual
Implemented in Ogre::SimplePageContentCollectionFactory.
Referenced by ~PageContentCollectionFactory().
The documentation for this class was generated from the following file:
OgrePageContentCollectionFactory.h