OGRE: Ogre::UserObjectBindings Class Reference
Ogre::UserObjectBindings Class Reference
Core » Scene
Class that provides convenient interface to establish a linkage between custom user application objects and Ogre core classes.
#include <OgreUserObjectBindings.h>
Public Member Functions
UserObjectBindings ()
Class constructor.
UserObjectBindings (const UserObjectBindings &other)
Copy constructor.
~UserObjectBindings ()
Class destructor.
void clear () const
Clear all user objects from this binding.
void eraseUserAny (const String &key)
Erase the custom user object associated with this class and key from this binding.
const Any & getUserAny (void) const
Retrieves the custom key less user object associated with this class.
const Any & getUserAny (const String &key) const
Retrieves the custom user object associated with this class and key.
UserObjectBindings & operator= (const UserObjectBindings &rhs)
void setUserAny (const Any &anything)
Sets any kind of user object on this class instance.
void setUserAny (const String &key, const Any &anything)
Sets any kind of user object on this class instance.
UserObjectBindings & swap (UserObjectBindings &rhs)
Static Public Member Functions
static const Any & getEmptyUserAny ()
Returns empty user any object.
Detailed Description
Class that provides convenient interface to establish a linkage between custom user application objects and Ogre core classes.
Any instance of Ogre class that will derive from this class could be associated with custom application object using this class interface.
Constructor & Destructor Documentation
Ogre::UserObjectBindings::UserObjectBindings ()
Class constructor.
Ogre::UserObjectBindings::~UserObjectBindings ()
Class destructor.
Ogre::UserObjectBindings::UserObjectBindings (const UserObjectBindings & other)
Copy constructor.
Performs a copy of all stored UserAny.
Member Function Documentation
void Ogre::UserObjectBindings::setUserAny (const Any & anything)
Sets any kind of user object on this class instance.
Remarks
This method allows you to associate any user object you like with this class. This can be a pointer back to one of your own classes for instance.
Note
This method is key less meaning that each call for it will override previous object that were set. If you need to associate multiple objects with this class use the extended version that takes key.
const Any& Ogre::UserObjectBindings::getUserAny (void) const
Retrieves the custom key less user object associated with this class.
void Ogre::UserObjectBindings::setUserAny (const String & key, const Any & anything)
Sets any kind of user object on this class instance.
Remarks
This method allows you to associate multiple object with this class. This can be a pointer back to one of your own classes for instance. Use a unique key to distinguish between each of these objects.
Parameters
key The key that this data is associate with.
anything The data to associate with the given key.
const Any& Ogre::UserObjectBindings::getUserAny (const String & key) const
Retrieves the custom user object associated with this class and key.
Parameters
key The key that the requested user object is associated with.
Remarks
In case no object associated with this key the returned Any object will be empty.
void Ogre::UserObjectBindings::eraseUserAny (const String & key)
Erase the custom user object associated with this class and key from this binding.
Parameters
key The key that the requested user object is associated with.
void Ogre::UserObjectBindings::clear () const
Clear all user objects from this binding.
static const Any& Ogre::UserObjectBindings::getEmptyUserAny () inline static
Returns empty user any object.
UserObjectBindings& Ogre::UserObjectBindings::swap (UserObjectBindings & rhs) inline
References std::swap().
Referenced by operator=().
UserObjectBindings& Ogre::UserObjectBindings::operator= (const UserObjectBindings & rhs) inline
References Ogre::MEMCATEGORY_GENERAL, OGRE_DELETE_T, OGRE_NEW_T, and swap().
The documentation for this class was generated from the following file:
OgreUserObjectBindings.h