OGRE: Ogre::SkeletonInstance Class Reference
Ogre::SkeletonInstance Class Reference
Core » Scene
A SkeletonInstance is a single instance of a Skeleton used by a world object.
#include <OgreSkeletonInstance.h>
Public Types
typedef vector< ushort >::type BoneHandleMap
Map to translate bone handle from one skeleton to another skeleton.
typedef VectorIterator< BoneList > BoneIterator
typedef vector< Bone * >::type BoneList
typedef ConstVectorIterator< LinkedSkeletonAnimSourceList > LinkedSkeletonAnimSourceIterator
typedef vector< LinkedSkeletonAnimationSource >::type LinkedSkeletonAnimSourceList
enum LoadingFlags {
LF_DEFAULT = 0, LF_INCLUDE_NON_RELOADABLE = 1, LF_ONLY_UNREFERENCED = 2, LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE = 3,
LF_PRESERVE_STATE = 4
}
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
enum LoadingState {
LOADSTATE_UNLOADED, LOADSTATE_LOADING, LOADSTATE_LOADED, LOADSTATE_UNLOADING,
LOADSTATE_PREPARED, LOADSTATE_PREPARING
}
Enum identifying the loading state of the resource.
Public Member Functions
SkeletonInstance (const SkeletonPtr &masterCopy)
Constructor, don't call directly, this will be created automatically when you create an Entity based on a skeletally animated Mesh.
~SkeletonInstance ()
virtual void _buildMapBoneByHandle (const Skeleton *source, BoneHandleMap &boneHandleMap) const
Build the bone handle map to use with Skeleton::_mergeSkeletonAnimations.
virtual void _buildMapBoneByName (const Skeleton *source, BoneHandleMap &boneHandleMap) const
Build the bone handle map to use with Skeleton::_mergeSkeletonAnimations.
virtual void _dirtyState ()
Manually mark the state of this resource as having been changed.
virtual void _fireLoadingComplete (bool wasBackgroundLoaded)
Firing of loading complete event.
virtual void _firePreparingComplete (bool wasBackgroundLoaded)
Firing of preparing complete event.
virtual void _fireUnloadingComplete (void)
Firing of unloading complete event.
Animation * _getAnimationImpl (const String &name, const LinkedSkeletonAnimationSource **linker=0) const
Internal accessor for animations (returns null if animation does not exist)
virtual void _getBoneMatrices (Matrix4 *pMatrices)
Populates the passed in array with the bone matrices based on the current position.
void _initAnimationState (AnimationStateSet *animSet)
Initialise an animation set suitable for use with this skeleton.
virtual void _mergeSkeletonAnimations (const Skeleton *source, const BoneHandleMap &boneHandleMap, const StringVector &animations=StringVector())
Merge animations from another Skeleton object into this skeleton.
virtual void _notifyManualBonesDirty (void)
Internal method for marking the manual bones as dirty.
virtual void _notifyManualBoneStateChange (Bone *bone)
Internal method for notifying that a bone is manual.
virtual void _notifyOrigin (const String &origin)
Notify this resource of it's origin.
void _refreshAnimationState (AnimationStateSet *animSet)
Refresh an animation set suitable for use with this skeleton.
virtual void _updateTransforms (void)
Updates all the derived transforms in the skeleton.
void addLinkedSkeletonAnimationSource (const String &skelName, Real scale=1.0f)
Allows you to use the animations from another Skeleton object to animate this skeleton.
virtual void addListener (Listener *lis)
Register a listener on this resource.
virtual void changeGroupOwnership (const String &newGroup)
Change the resource group ownership of a Resource.
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
Animation * createAnimation (const String &name, Real length)
Creates a new Animation object for animating this skeleton.
virtual Bone * createBone (void)
Creates a brand new Bone owned by this Skeleton.
virtual Bone * createBone (unsigned short handle)
Creates a brand new Bone owned by this Skeleton.
virtual Bone * createBone (const String &name)
Creates a brand new Bone owned by this Skeleton.
virtual Bone * createBone (const String &name, unsigned short handle)
Creates a brand new Bone owned by this Skeleton.
TagPoint * createTagPointOnBone (Bone *bone, const Quaternion &offsetOrientation=Quaternion::IDENTITY, const Vector3 &offsetPosition=Vector3::ZERO)
Creates a TagPoint ready to be attached to a bone.
virtual void escalateLoading ()
Escalates the loading of a background loaded resource.
void freeTagPoint (TagPoint *tagPoint)
Frees a TagPoint that already attached to a bone.
Animation * getAnimation (unsigned short index) const
Gets a single animation by index.
Animation * getAnimation (const String &name, const LinkedSkeletonAnimationSource **linker=0) const
Returns the named Animation object.
virtual Animation * getAnimation (const String &name) const
Returns the named Animation object.
virtual SkeletonAnimationBlendMode getBlendMode () const
Gets the animation blending mode which this skeleton will use.
virtual Bone * getBone (unsigned short handle) const
Gets a bone by it's handle.
virtual Bone * getBone (const String &name) const
Gets a bone by it's name.
virtual BoneIterator getBoneIterator (void)
Get an iterator over all the bones in the skeleton.
const BoneList & getBones () const
Get all the bones in the skeleton.
virtual ResourceManager * getCreator (void)
Gets the manager which created this resource.
const String & getGroup (void) const
Gets the group which this resource is a member of.
ResourceHandle getHandle (void) const
LinkedSkeletonAnimSourceIterator getLinkedSkeletonAnimationSourceIterator (void) const
Get an iterator over the linked skeletons used as animation sources.
virtual LoadingState getLoadingState () const
Returns the current loading state.
virtual bool getManualBonesDirty (void) const
Have manual bones been modified since the skeleton was last updated?
const String & getName (void) const
Gets resource name.
unsigned short getNumAnimations (void) const
Gets the number of animations on this skeleton.
virtual unsigned short getNumBones (void) const
Returns the number of bones in this skeleton.
virtual const String & getOrigin (void) const
Get the origin of this resource, e.g.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
virtual Bone * getRootBone (void) const
Gets the root bone of the skeleton.
virtual BoneIterator getRootBoneIterator (void)
Get an iterator over the root bones in the skeleton, ie those with no parents.
const BoneList & getRootBones () const
Get the root bones in the skeleton, ie those with no parents.
virtual size_t getSize (void) const
Retrieves info about the size of the resource.
virtual size_t getStateCount () const
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
virtual bool hasAnimation (const String &name) const
Returns whether this skeleton contains the named animation.
virtual bool hasBone (const String &name) const
Returns whether this skeleton contains the named bone.
virtual bool hasManualBones (void) const
Are there any manually controlled bones?
virtual bool isBackgroundLoaded (void) const
Returns whether this Resource has been earmarked for background loading.
virtual bool isLoaded (void) const
Returns true if the Resource has been loaded, false otherwise.
virtual bool isLoading () const
Returns whether the resource is currently in the process of background loading.
virtual bool isManuallyLoaded (void) const
Is this resource manually loaded?
virtual bool isPrepared (void) const
Returns true if the Resource has been prepared, false otherwise.
virtual bool isReloadable (void) const
Returns true if the Resource is reloadable, false otherwise.
virtual void load (bool backgroundThread=false)
Loads the resource, if it is not already.
virtual void optimiseAllAnimations (bool preservingIdentityNodeTracks=false)
Optimise all of this skeleton's animations.
virtual void prepare (bool backgroundThread=false)
Prepares the resource for load, if it is not already.
virtual void reload (LoadingFlags flags=LF_DEFAULT)
Reloads the resource, if it is already loaded.
void removeAllLinkedSkeletonAnimationSources (void)
Remove all links to other skeletons for the purposes of sharing animation.
void removeAnimation (const String &name)
Removes an Animation from this skeleton.
virtual void removeListener (Listener *lis)
Remove a listener on this resource.
virtual void reset (bool resetManualBones=false)
Resets the position and orientation of all bones in this skeleton to their original binding position.
virtual void setAnimationState (const AnimationStateSet &animSet)
Changes the state of the skeleton to reflect the application of the passed in collection of animations.
virtual void setBackgroundLoaded (bool bl)
Tells the resource whether it is background loaded or not.
virtual void setBindingPose (void)
Sets the current position / orientation to be the 'binding pose' i.e.
virtual void setBlendMode (SkeletonAnimationBlendMode state)
Sets the animation blending mode this skeleton will use.
virtual void setManuallyLoaded (bool isManual)
Set "Is this resource manually loaded?".
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
virtual void setToLoaded (void)
Change the Resource loading state to loaded.
virtual void touch (void)
'Touches' the resource to indicate it has been used.
virtual void unload (void)
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Public Attributes
OGRE_AUTO_MUTEX
Detailed Description
A SkeletonInstance is a single instance of a Skeleton used by a world object.
Remarks
The difference between a Skeleton and a SkeletonInstance is that the Skeleton is the 'master' version much like Mesh is a 'master' version of Entity. Many SkeletonInstance objects can be based on a single Skeleton, and are copies of it when created. Any changes made to this are not reflected in the master copy. The exception is animations; these are shared on the Skeleton itself and may not be modified here.
Member Typedef Documentation
typedef vector<Bone*>::type Ogre::Skeleton::BoneList inherited
typedef VectorIterator<BoneList> Ogre::Skeleton::BoneIterator inherited
typedef vector<LinkedSkeletonAnimationSource>::type Ogre::Skeleton::LinkedSkeletonAnimSourceList inherited
typedef ConstVectorIterator<LinkedSkeletonAnimSourceList> Ogre::Skeleton::LinkedSkeletonAnimSourceIterator inherited
typedef vector<ushort>::type Ogre::Skeleton::BoneHandleMap inherited
Map to translate bone handle from one skeleton to another skeleton.
Member Enumeration Documentation
enum Ogre::Resource::LoadingState inherited
Enum identifying the loading state of the resource.
Enumerator
LOADSTATE_UNLOADED
Not loaded.
LOADSTATE_LOADING
Loading is in progress.
LOADSTATE_LOADED
Fully loaded.
LOADSTATE_UNLOADING
Currently unloading.
LOADSTATE_PREPARED
Fully prepared.
LOADSTATE_PREPARING
Preparing is in progress.
enum Ogre::Resource::LoadingFlags inherited
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
Enumerator
LF_DEFAULT
Only reloadable resources are processed, reload restores initial state.
LF_INCLUDE_NON_RELOADABLE
Process non-reloadable resources too.
LF_ONLY_UNREFERENCED
Process only resources which are not referenced by any other object. Usefull to reduce resource consumption.
LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE
Combination of LF_ONLY_UNREFERENCED and LF_INCLUDE_NON_RELOADABLE.
LF_PRESERVE_STATE
Preserve some states during reloading, for example stencil shadows prepareness for Meshes.
Constructor & Destructor Documentation
Ogre::SkeletonInstance::SkeletonInstance (const SkeletonPtr & masterCopy)
Constructor, don't call directly, this will be created automatically when you create an Entity based on a skeletally animated Mesh.
Ogre::SkeletonInstance::~SkeletonInstance ()
Member Function Documentation
unsigned short Ogre::SkeletonInstance::getNumAnimations (void) const virtual
Gets the number of animations on this skeleton.
Reimplemented from Ogre::Skeleton.
Animation* Ogre::SkeletonInstance::getAnimation (unsigned short index) const virtual
Gets a single animation by index.
Reimplemented from Ogre::Skeleton.
Animation* Ogre::SkeletonInstance::_getAnimationImpl (const String & name, const LinkedSkeletonAnimationSource ** linker = 0) const virtual
Internal accessor for animations (returns null if animation does not exist)
Reimplemented from Ogre::Skeleton.
Animation* Ogre::SkeletonInstance::createAnimation (const String & name, Real length) virtual
Creates a new Animation object for animating this skeleton.
Remarks
This method updates the reference skeleton, not just this instance!
Parameters
name The name of this animation
length The length of the animation in seconds
Reimplemented from Ogre::Skeleton.
Animation* Ogre::SkeletonInstance::getAnimation (const String & name, const LinkedSkeletonAnimationSource ** linker = 0) const virtual
Returns the named Animation object.
Reimplemented from Ogre::Skeleton.
void Ogre::SkeletonInstance::removeAnimation (const String & name) virtual
Removes an Animation from this skeleton.
Remarks
This method updates the reference skeleton, not just this instance!
Reimplemented from Ogre::Skeleton.
TagPoint* Ogre::SkeletonInstance::createTagPointOnBone (Bone * bone, const Quaternion & offsetOrientation = Quaternion::IDENTITY, const Vector3 & offsetPosition = Vector3::ZERO)
Creates a TagPoint ready to be attached to a bone.
void Ogre::SkeletonInstance::freeTagPoint (TagPoint * tagPoint)
Frees a TagPoint that already attached to a bone.
void Ogre::SkeletonInstance::addLinkedSkeletonAnimationSource (const String & skelName, Real scale = 1.0f) virtual
Allows you to use the animations from another Skeleton object to animate this skeleton.
Remarks
If you have skeletons of identical structure (that means identically named bones with identical handles, and with the same hierarchy), but slightly different proportions or binding poses, you can re-use animations from one in the other. Because animations are actually stored as changes to bones from their bind positions, it's possible to use the same animation data for different skeletons, provided the skeletal structure matches and the 'deltas' stored in the keyframes apply equally well to the other skeletons bind position (so they must be roughly similar, but don't have to be identical). You can use the 'scale' option to adjust the translation and scale keyframes where there are large differences in size between the skeletons.
Note
This method takes a skeleton name, rather than a more specific animation name, for two reasons; firstly it allows some validation of compatibility of skeletal structure, and secondly skeletons are the unit of loading. Linking a skeleton to another in this way means that the linkee will be prevented from being destroyed until the linker is destroyed.
You cannot set up cyclic relationships, e.g. SkeletonA uses SkeletonB's animations, and SkeletonB uses SkeletonA's animations. This is because it would set up a circular dependency which would prevent proper unloading - make one of the skeletons the 'master' in this case.
Parameters
skelName Name of the skeleton to link animations from. This skeleton will be loaded immediately if this skeleton is already loaded, otherwise it will be loaded when this skeleton is.
scale A scale factor to apply to translation and scaling elements of the keyframes in the other skeleton when applying the animations to this one. Compensates for skeleton size differences.
Reimplemented from Ogre::Skeleton.
void Ogre::SkeletonInstance::removeAllLinkedSkeletonAnimationSources (void) virtual
Remove all links to other skeletons for the purposes of sharing animation.
Reimplemented from Ogre::Skeleton.
LinkedSkeletonAnimSourceIterator Ogre::SkeletonInstance::getLinkedSkeletonAnimationSourceIterator (void) const virtual
Get an iterator over the linked skeletons used as animation sources.
Reimplemented from Ogre::Skeleton.
void Ogre::SkeletonInstance::_initAnimationState (AnimationStateSet * animSet) virtual
Initialise an animation set suitable for use with this skeleton.
Remarks
Only recommended for use inside the engine, not by applications.
Reimplemented from Ogre::Skeleton.
void Ogre::SkeletonInstance::_refreshAnimationState (AnimationStateSet * animSet) virtual
Refresh an animation set suitable for use with this skeleton.
Remarks
Only recommended for use inside the engine, not by applications.
Reimplemented from Ogre::Skeleton.
const String& Ogre::SkeletonInstance::getName (void) const virtual
Gets resource name.
Reimplemented from Ogre::Resource.
ResourceHandle Ogre::SkeletonInstance::getHandle (void) const virtual
Reimplemented from Ogre::Resource.
const String& Ogre::SkeletonInstance::getGroup (void) const virtual
Gets the group which this resource is a member of.
Reimplemented from Ogre::Resource.
virtual Bone* Ogre::Skeleton::createBone (void) virtual inherited
Creates a brand new Bone owned by this Skeleton.
Remarks
This method creates an unattached new Bone for this skeleton. Unless this is to be a root bone (there may be more than one of these), you must attach it to another Bone in the skeleton using addChild for it to be any use. For this reason you will likely be better off creating child bones using the Bone::createChild method instead, once you have created the root bone.
Note that this method automatically generates a handle for the bone, which you can retrieve using Bone::getHandle. If you wish the new Bone to have a specific handle, use the alternate form of this method which takes a handle as a parameter, although you should note the restrictions.
virtual Bone* Ogre::Skeleton::createBone (unsigned short handle) virtual inherited
Creates a brand new Bone owned by this Skeleton.
Remarks
This method creates an unattached new Bone for this skeleton and assigns it a specific handle. Unless this is to be a root bone (there may be more than one of these), you must attach it to another Bone in the skeleton using addChild for it to be any use. For this reason you will likely be better off creating child bones using the Bone::createChild method instead, once you have created a root bone.
Parameters
handle The handle to give to this new bone - must be unique within this skeleton. You should also ensure that all bone handles are eventually contiguous (this is to simplify their compilation into an indexed array of transformation matrices). For this reason it is advised that you use the simpler createBone method which automatically assigns a sequential handle starting from 0.
virtual Bone* Ogre::Skeleton::createBone (const String & name) virtual inherited
Creates a brand new Bone owned by this Skeleton.
Remarks
This method creates an unattached new Bone for this skeleton and assigns it a specific name.Unless this is to be a root bone (there may be more than one of these), you must attach it to another Bone in the skeleton using addChild for it to be any use. For this reason you will likely be better off creating child bones using the Bone::createChild method instead, once you have created the root bone.
Parameters
name The name to give to this new bone - must be unique within this skeleton. Note that the way OGRE looks up bones is via a numeric handle, so if you name a Bone this way it will be given an automatic sequential handle. The name is just for your convenience, although it is recommended that you only use the handle to retrieve the bone in performance-critical code.
virtual Bone* Ogre::Skeleton::createBone (const String & name, unsigned short handle) virtual inherited
Creates a brand new Bone owned by this Skeleton.
Remarks
This method creates an unattached new Bone for this skeleton and assigns it a specific name and handle. Unless this is to be a root bone (there may be more than one of these), you must attach it to another Bone in the skeleton using addChild for it to be any use. For this reason you will likely be better off creating child bones using the Bone::createChild method instead, once you have created the root bone.
Parameters
name The name to give to this new bone - must be unique within this skeleton.
handle The handle to give to this new bone - must be unique within this skeleton.
virtual unsigned short Ogre::Skeleton::getNumBones (void) const virtual inherited
Returns the number of bones in this skeleton.
virtual Bone* Ogre::Skeleton::getRootBone (void) const inline virtual inherited
Gets the root bone of the skeleton.
Deprecated:
use Skeleton::getRootBones
virtual BoneIterator Ogre::Skeleton::getRootBoneIterator (void) virtual inherited
Get an iterator over the root bones in the skeleton, ie those with no parents.
Deprecated:
use Skeleton::getRootBones
const BoneList& Ogre::Skeleton::getRootBones () const inherited
Get the root bones in the skeleton, ie those with no parents.
The system derives the root bone the first time you ask for it. The root bone is the only bone in the skeleton which has no parent. The system locates it by taking the first bone in the list and going up the bone tree until there are no more parents, and saves this top bone as the root. If you are building the skeleton manually using createBone then you must ensure there is only one bone which is not a child of another bone, otherwise your skeleton will not work properly. If you use createBone only once, and then use Bone::createChild from then on, then inherently the first bone you create will by default be the root.
virtual BoneIterator Ogre::Skeleton::getBoneIterator (void) virtual inherited
Get an iterator over all the bones in the skeleton.
Deprecated:
use getBones()
const BoneList& Ogre::Skeleton::getBones () const inline inherited
Get all the bones in the skeleton.
virtual Bone* Ogre::Skeleton::getBone (unsigned short handle) const virtual inherited
Gets a bone by it's handle.
virtual Bone* Ogre::Skeleton::getBone (const String & name) const virtual inherited
Gets a bone by it's name.
virtual bool Ogre::Skeleton::hasBone (const String & name) const virtual inherited
Returns whether this skeleton contains the named bone.
virtual void Ogre::Skeleton::setBindingPose (void) virtual inherited
Sets the current position / orientation to be the 'binding pose' i.e.
the layout in which bones were originally bound to a mesh.
virtual void Ogre::Skeleton::reset (bool resetManualBones = false) virtual inherited
Resets the position and orientation of all bones in this skeleton to their original binding position.
Remarks
A skeleton is bound to a mesh in a binding pose. Bone positions are then modified from this position during animation. This method returns all the bones to their original position and orientation.
Parameters
resetManualBones If set to true, causes the state of manual bones to be reset too, which is normally not done to allow the manual state to persist even when keyframe animation is applied.
virtual Animation* Ogre::Skeleton::getAnimation (const String & name) const virtual inherited
Returns the named Animation object.
Remarks
Will pick up animations in linked skeletons (
See also
addLinkedSkeletonAnimationSource).
Parameters
name The name of the animation
Implements Ogre::AnimationContainer.
virtual bool Ogre::Skeleton::hasAnimation (const String & name) const virtual inherited
Returns whether this skeleton contains the named animation.
Implements Ogre::AnimationContainer.
virtual void Ogre::Skeleton::setAnimationState (const AnimationStateSet & animSet) virtual inherited
Changes the state of the skeleton to reflect the application of the passed in collection of animations.
Remarks
Animating a skeleton involves both interpolating between keyframes of a specific animation, and blending between the animations themselves. Calling this method sets the state of the skeleton so that it reflects the combination of all the passed in animations, at the time index specified for each, using the weights specified. Note that the weights between animations do not have to sum to 1.0, because some animations may affect only subsets of the skeleton. If the weights exceed 1.0 for the same area of the skeleton, the movement will just be exaggerated.
virtual void Ogre::Skeleton::_getBoneMatrices (Matrix4 * pMatrices) virtual inherited
Populates the passed in array with the bone matrices based on the current position.
Remarks
Internal use only. The array pointed to by the passed in pointer must be at least as large as the number of bones. Assumes animation has already been updated.
virtual SkeletonAnimationBlendMode Ogre::Skeleton::getBlendMode () const virtual inherited
Gets the animation blending mode which this skeleton will use.
virtual void Ogre::Skeleton::setBlendMode (SkeletonAnimationBlendMode state) virtual inherited
Sets the animation blending mode this skeleton will use.
virtual void Ogre::Skeleton::_updateTransforms (void) virtual inherited
Updates all the derived transforms in the skeleton.
virtual void Ogre::Skeleton::optimiseAllAnimations (bool preservingIdentityNodeTracks = false) virtual inherited
Optimise all of this skeleton's animations.
See also
Animation::optimise
Parameters
preservingIdentityNodeTracks If true, don't destroy identity node tracks.
virtual void Ogre::Skeleton::_notifyManualBonesDirty (void) virtual inherited
Internal method for marking the manual bones as dirty.
virtual void Ogre::Skeleton::_notifyManualBoneStateChange (Bone * bone) virtual inherited
Internal method for notifying that a bone is manual.
virtual bool Ogre::Skeleton::getManualBonesDirty (void) const inline virtual inherited
Have manual bones been modified since the skeleton was last updated?
virtual bool Ogre::Skeleton::hasManualBones (void) const inline virtual inherited
Are there any manually controlled bones?
virtual void Ogre::Skeleton::_mergeSkeletonAnimations (const Skeleton * source, const BoneHandleMap & boneHandleMap, const StringVector & animations = StringVector()) virtual inherited
Merge animations from another Skeleton object into this skeleton.
Remarks
This function allow merge two structures compatible skeletons. The 'compatible' here means identically bones will have same hierarchy, but skeletons are not necessary to have same number of bones (if number bones of source skeleton's more than this skeleton, they will copied as is, except that duplicate names are disallowed; and in the case of bones missing in source skeleton, nothing happen for those bones).
There are also unnecessary to have same binding poses, this function will adjust keyframes of the source skeleton to match this skeleton automatically.
It's useful for exporting skeleton animations separately. i.e. export mesh and 'master' skeleton at the same time, and then other animations will export separately (even if used completely difference binding pose), finally, merge separately exported animations into 'master' skeleton.
Parameters
source Pointer to source skeleton. It'll keep unmodified.
boneHandleMap A map to translate identically bone's handle from source skeleton to this skeleton. If mapped bone handle doesn't exists in this skeleton, it'll created. You can populate bone handle map manually, or use predefined functions build bone handle map for you. (
See also
_buildMapBoneByHandle, _buildMapBoneByName)
Parameters
animations A list name of animations to merge, if empty, all animations of source skeleton are used to merge. Note that the animation names must not presented in this skeleton, and will NOT pick up animations in linked skeletons (
See also
addLinkedSkeletonAnimationSource).
virtual void Ogre::Skeleton::_buildMapBoneByHandle (const Skeleton * source, BoneHandleMap & boneHandleMap) const virtual inherited
Build the bone handle map to use with Skeleton::_mergeSkeletonAnimations.
Remarks
Identically bones are determine by handle.
virtual void Ogre::Skeleton::_buildMapBoneByName (const Skeleton * source, BoneHandleMap & boneHandleMap) const virtual inherited
Build the bone handle map to use with Skeleton::_mergeSkeletonAnimations.
Remarks
Identically bones are determine by name.
virtual void Ogre::Resource::prepare (bool backgroundThread = false) virtual inherited
Prepares the resource for load, if it is not already.
One can call prepare() before load(), but this is not required as load() will call prepare() itself, if needed. When OGRE_THREAD_SUPPORT==1 both load() and prepare() are thread-safe. When OGRE_THREAD_SUPPORT==2 however, only prepare() is thread-safe. The reason for this function is to allow a background thread to do some of the loading work, without requiring the whole render system to be thread-safe. The background thread would call prepare() while the main render loop would later call load(). So long as prepare() remains thread-safe, subclasses can arbitrarily split the work of loading a resource between load() and prepare(). It is best to try and do as much work in prepare(), however, since this will leave less work for the main render thread to do and thus increase FPS.
Parameters
backgroundThread Whether this is occurring in a background thread
virtual void Ogre::Resource::load (bool backgroundThread = false) virtual inherited
Loads the resource, if it is not already.
Remarks
If the resource is loaded from a file, loading is automatic. If not, if for example this resource gained it's data from procedural calls rather than loading from a file, then this resource will not reload on it's own.
Parameters
backgroundThread Indicates whether the caller of this method is the background resource loading thread.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::reload (LoadingFlags flags = LF_DEFAULT) virtual inherited
Reloads the resource, if it is already loaded.
Remarks
Calls unload() and then load() again, if the resource is already loaded. If it is not loaded already, then nothing happens.
Reimplemented in Ogre::Mesh, and Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::Resource::isReloadable (void) const inline virtual inherited
Returns true if the Resource is reloadable, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::Resource::isManuallyLoaded (void) const inline virtual inherited
Is this resource manually loaded?
virtual void Ogre::Resource::setManuallyLoaded (bool isManual) inline virtual inherited
Set "Is this resource manually loaded?".
virtual void Ogre::Resource::unload (void) virtual inherited
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual size_t Ogre::Resource::getSize (void) const inline virtual inherited
Retrieves info about the size of the resource.
Reimplemented in Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::touch (void) virtual inherited
'Touches' the resource to indicate it has been used.
Reimplemented in Ogre::Material, Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
Referenced by Ogre::Material::touch().
virtual bool Ogre::Resource::isPrepared (void) const inline virtual inherited
Returns true if the Resource has been prepared, false otherwise.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isLoaded (void) const inline virtual inherited
Returns true if the Resource has been loaded, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual void Ogre::Resource::setToLoaded (void) inline virtual inherited
Change the Resource loading state to loaded.
References Ogre::AtomicScalar< T >::set().
virtual bool Ogre::Resource::isLoading () const inline virtual inherited
Returns whether the resource is currently in the process of background loading.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual LoadingState Ogre::Resource::getLoadingState () const inline virtual inherited
Returns the current loading state.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isBackgroundLoaded (void) const inline virtual inherited
Returns whether this Resource has been earmarked for background loading.
Remarks
This option only makes sense when you have built Ogre with thread support (OGRE_THREAD_SUPPORT). If a resource has been marked for background loading, then it won't load on demand like normal when load() is called. Instead, it will ignore request to load() except if the caller indicates it is the background loader. Any other users of this resource should check isLoaded(), and if that returns false, don't use the resource and come back later.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::setBackgroundLoaded (bool bl) inline virtual inherited
Tells the resource whether it is background loaded or not.
See also
Resource::isBackgroundLoaded. Note that calling this only defers the normal on-demand loading behaviour of a resource, it does not actually set up a thread to make sure the resource gets loaded in the background. You should use ResourceBackgroundLoadingQueue to manage the actual loading (which will call this method itself).
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::escalateLoading () virtual inherited
Escalates the loading of a background loaded resource.
Remarks
If a resource is set to load in the background, but something needs it before it's been loaded, there could be a problem. If the user of this resource really can't wait, they can escalate the loading which basically pulls the loading into the current thread immediately. If the resource is already being loaded but just hasn't quite finished then this method will simply wait until the background load is complete.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::addListener (Listener * lis) virtual inherited
Register a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::removeListener (Listener * lis) virtual inherited
Remove a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::changeGroupOwnership (const String & newGroup) virtual inherited
Change the resource group ownership of a Resource.
Remarks
This method is generally reserved for internal use, although if you really know what you're doing you can use it to move this resource from one group to another.
Parameters
newGroup Name of the new group
virtual ResourceManager* Ogre::Resource::getCreator (void) inline virtual inherited
Gets the manager which created this resource.
virtual const String& Ogre::Resource::getOrigin (void) const inline virtual inherited
Get the origin of this resource, e.g.
a script file name.
Remarks
This property will only contain something if the creator of this resource chose to populate it. Script loaders are advised to populate it.
virtual void Ogre::Resource::_notifyOrigin (const String & origin) inline virtual inherited
Notify this resource of it's origin.
virtual size_t Ogre::Resource::getStateCount () const inline virtual inherited
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
Objects that build derived data based on the resource can check this value against a copy they kept last time they built this derived data, in order to know whether it needs rebuilding. This is a nice way of monitoring changes without having a tightly-bound callback.
virtual void Ogre::Resource::_dirtyState () virtual inherited
Manually mark the state of this resource as having been changed.
Remarks
You only need to call this from outside if you explicitly want derived objects to think this object has changed.
See also
getStateCount.
virtual void Ogre::Resource::_fireLoadingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of loading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
virtual void Ogre::Resource::_firePreparingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of preparing complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
virtual void Ogre::Resource::_fireUnloadingComplete (void) virtual inherited
Firing of unloading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
virtual String Ogre::StringInterface::getParameter (const String & name) const inline virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
Member Data Documentation
Ogre::Resource::OGRE_AUTO_MUTEX inherited
The documentation for this class was generated from the following file:
OgreSkeletonInstance.h