OGRE: Ogre::MovablePlane Class Reference
Ogre::MovablePlane Class Reference
Core » Scene
Definition of a Plane that may be attached to a node, and the derived details of it retrieved simply.
#include <OgreMovablePlane.h>
Public Types
typedef vector< ShadowRenderable * >::type ShadowRenderableList
typedef VectorIterator< ShadowRenderableList > ShadowRenderableListIterator
enum Side { NO_SIDE, POSITIVE_SIDE, NEGATIVE_SIDE, BOTH_SIDE }
The "positive side" of the plane is the half space to which the plane normal points.
Public Member Functions
MovablePlane (const String &name)
MovablePlane (const Plane &rhs)
MovablePlane (const Vector3 &rkNormal, Real fConstant)
Construct a plane through a normal, and a distance to move the plane along the normal.
MovablePlane (const Vector3 &rkNormal, const Vector3 &rkPoint)
MovablePlane (const Vector3 &rkPoint0, const Vector3 &rkPoint1, const Vector3 &rkPoint2)
~MovablePlane ()
MovableObjectFactory * _getCreator (void) const
Get the creator of this object, if any (internal use only)
const Plane & _getDerivedPlane (void) const
Get the derived plane as transformed by its parent node.
LightList * _getLightList ()
Returns a pointer to the current list of lights for this object.
SceneManager * _getManager (void) const
Get the manager of this object, if any (internal use only)
virtual const Matrix4 & _getParentNodeFullTransform (void) const
Return the full transformation of the parent sceneNode or the attachingPoint node.
virtual void _notifyAttached (Node *parent, bool isTagPoint=false)
Internal method called to notify the object that it has been attached to a node.
virtual void _notifyCreator (MovableObjectFactory *fact)
Notify the object of it's creator (internal use only)
void _notifyCurrentCamera (Camera *)
Overridden from MovableObject.
virtual void _notifyManager (SceneManager *man)
Notify the object of it's manager (internal use only)
virtual void _notifyMoved (void)
Internal method called to notify the object that it has been moved.
virtual void _releaseManualHardwareResources ()
Notifies the movable object that hardware resources were lost.
virtual void _restoreManualHardwareResources ()
Notifies the movable object that hardware resources should be restored.
void _updateRenderQueue (RenderQueue *)
Overridden from MovableObject.
void addQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
void addVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
virtual AnimableValuePtr createAnimableValue (const String &valueName)
Create a reference-counted AnimableValuePtr for the named value.
void detachFromParent (void)
Detaches an object from a parent SceneNode or TagPoint, if attached.
const StringVector & getAnimableValueNames (void) const
Gets a list of animable value names for this object.
const AxisAlignedBox & getBoundingBox (void) const
Overridden from MovableObject.
Real getBoundingRadius (void) const
Overridden from MovableObject.
bool getCastShadows (void) const
Returns whether shadow casting is enabled for this object.
const AxisAlignedBox & getDarkCapBounds (const Light &light, Real dirLightExtrusionDist) const
Overridden member from ShadowCaster.
Real getDistance (const Vector3 &rkPoint) const
This is a pseudodistance.
EdgeData * getEdgeList (void)
Returns details of the edges which might be used to determine a silhouette.
const AxisAlignedBox & getLightCapBounds (void) const
Overridden member from ShadowCaster.
uint32 getLightMask () const
Get a bitwise mask which will filter the lights affecting this object.
Listener * getListener (void) const
Gets the current listener for this object.
const String & getMovableType (void) const
Overridden from MovableObject.
const String & getName (void) const
Returns the name of this object.
Node * getParentNode (void) const
Returns the node to which this object is attached.
SceneNode * getParentSceneNode (void) const
Returns the scene node to which this object is attached.
Real getPointExtrusionDistance (const Light *l) const
Get the distance to extrude for a point/spot light.
uint32 getQueryFlags (void) const
Returns the query flags relevant for this object.
bool getReceivesShadows ()
Returns whether the Material of any Renderable that this MovableObject will add to the render queue will receive shadows.
Real getRenderingDistance (void) const
Gets the distance at which batches are no longer rendered.
Real getRenderingMinPixelSize () const
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
uint8 getRenderQueueGroup (void) const
Gets the queue group for this entity.
ShadowRenderableListIterator getShadowVolumeRenderableIterator (ShadowTechnique shadowTechnique, const Light *light, HardwareIndexBufferSharedPtr *indexBuffer, size_t *indexBufferUsedSize, bool extrudeVertices, Real extrusionDist, unsigned long flags=0)
Define a default implementation of method from ShadowCaster which implements no shadows.
Side getSide (const Vector3 &rkPoint) const
Side getSide (const AxisAlignedBox &rkBox) const
Returns the side where the alignedBox is.
Side getSide (const Vector3 &centre, const Vector3 &halfSize) const
Returns which side of the plane that the given box lies on.
virtual uint32 getTypeFlags (void) const
Get the 'type flags' for this MovableObject.
const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
uint32 getVisibilityFlags (void) const
Returns the visibility flags relevant for this object.
bool getVisible (void) const
Gets this object whether to be visible or not, if it has a renderable component.
virtual const AxisAlignedBox & getWorldBoundingBox (bool derive=false) const
Retrieves the axis-aligned bounding box for this object in world coordinates.
virtual const Sphere & getWorldBoundingSphere (bool derive=false) const
Retrieves the worldspace bounding sphere for this object.
bool hasEdgeList (void)
Returns whether the object has a valid edge list.
bool isAttached (void) const
Returns true if this object is attached to a SceneNode or TagPoint.
bool isDebugDisplayEnabled (void) const
Gets whether debug display of this object is enabled.
virtual bool isInScene (void) const
Returns true if this object is attached to a SceneNode or TagPoint, and this SceneNode / TagPoint is currently in an active part of the scene graph.
bool isParentTagPoint () const
Gets whether the parent node is a TagPoint (or a SceneNode)
virtual bool isVisible (void) const
Returns whether or not this object is supposed to be visible or not.
Real normalise (void)
Normalises the plane.
bool operator!= (const Plane &rhs) const
Plane operator- () const
Get flipped plane, with same location but reverted orientation.
bool operator== (const Plane &rhs) const
Comparison operator.
Vector3 projectVector (const Vector3 &v) const
Project a vector onto the plane.
const LightList & queryLights (void) const
Gets a list of lights, ordered relative to how close they are to this movable object.
void redefine (const Vector3 &rkPoint0, const Vector3 &rkPoint1, const Vector3 &rkPoint2)
Redefine this plane based on 3 points.
void redefine (const Vector3 &rkNormal, const Vector3 &rkPoint)
Redefine this plane based on a normal and a point.
void removeQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
void removeVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
void setCastShadows (bool enabled)
Sets whether or not this object will cast shadows.
void setDebugDisplayEnabled (bool enabled)
Sets whether or not the debug display of this object is enabled.
void setLightMask (uint32 lightMask)
Set a bitwise mask which will filter the lights affecting this object.
void setListener (Listener *listener)
Sets a listener for this object.
void setQueryFlags (uint32 flags)
Sets the query flags for this object.
void setRenderingDistance (Real dist)
Sets the distance at which the object is no longer rendered.
void setRenderingMinPixelSize (Real pixelSize)
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
virtual void setRenderQueueGroup (uint8 queueID)
Sets the render queue group this entity will be rendered through.
virtual void setRenderQueueGroupAndPriority (uint8 queueID, ushort priority)
Sets the render queue group and group priority this entity will be rendered through.
void setUserAny (const Any &anything)
void setVisibilityFlags (uint32 flags)
Sets the visibility flags for this object.
void setVisible (bool visible)
Tells this object whether to be visible or not, if it has a renderable component.
void visitRenderables (Renderable::Visitor *visitor, bool debugRenderables=false)
Method to allow a caller to abstractly iterate over the Renderable instances that this MovableObject will add to the render queue when asked, if any.
Static Public Member Functions
static void clearShadowRenderableList (ShadowRenderableList &shadowRenderables)
Common implementation of releasing shadow renderables.
static void extrudeVertices (const HardwareVertexBufferSharedPtr &vertexBuffer, size_t originalVertexCount, const Vector4 &lightPos, Real extrudeDist)
Utility method for extruding vertices based on a light.
static uint32 getDefaultQueryFlags ()
Get the default query flags for all future MovableObject instances.
static uint32 getDefaultVisibilityFlags ()
Get the default visibility flags for all future MovableObject instances.
static void setDefaultQueryFlags (uint32 flags)
Set the default query flags for all future MovableObject instances.
static void setDefaultVisibilityFlags (uint32 flags)
Set the default visibility flags for all future MovableObject instances.
Public Attributes
Real d
Vector3 normal
Detailed Description
Definition of a Plane that may be attached to a node, and the derived details of it retrieved simply.
Remarks
This plane is not here for rendering purposes, it's to allow you to attach planes to the scene in order to have them move and follow nodes on their own, which is useful if you're using the plane for some kind of calculation, e.g. reflection.
Member Typedef Documentation
typedef vector<ShadowRenderable*>::type Ogre::ShadowCaster::ShadowRenderableList inherited
typedef VectorIterator<ShadowRenderableList> Ogre::ShadowCaster::ShadowRenderableListIterator inherited
Member Enumeration Documentation
enum Ogre::Plane::Side inherited
The "positive side" of the plane is the half space to which the plane normal points.
The "negative side" is the other half space. The flag "no side" indicates the plane itself.
Enumerator
NO_SIDE
POSITIVE_SIDE
NEGATIVE_SIDE
BOTH_SIDE
Constructor & Destructor Documentation
Ogre::MovablePlane::MovablePlane (const String & name)
Ogre::MovablePlane::MovablePlane (const Plane & rhs)
Ogre::MovablePlane::MovablePlane (const Vector3 & rkNormal, Real fConstant)
Construct a plane through a normal, and a distance to move the plane along the normal.
Ogre::MovablePlane::MovablePlane (const Vector3 & rkNormal, const Vector3 & rkPoint)
Ogre::MovablePlane::MovablePlane (const Vector3 & rkPoint0, const Vector3 & rkPoint1, const Vector3 & rkPoint2)
Ogre::MovablePlane::~MovablePlane () inline
Member Function Documentation
void Ogre::MovablePlane::_notifyCurrentCamera (Camera *) inline virtual
Overridden from MovableObject.
Reimplemented from Ogre::MovableObject.
const AxisAlignedBox& Ogre::MovablePlane::getBoundingBox (void) const inline virtual
Overridden from MovableObject.
Implements Ogre::MovableObject.
Real Ogre::MovablePlane::getBoundingRadius (void) const inline virtual
Overridden from MovableObject.
Implements Ogre::MovableObject.
void Ogre::MovablePlane::_updateRenderQueue (RenderQueue *) inline virtual
Overridden from MovableObject.
Implements Ogre::MovableObject.
const String& Ogre::MovablePlane::getMovableType (void) const virtual
Overridden from MovableObject.
Implements Ogre::MovableObject.
const Plane& Ogre::MovablePlane::_getDerivedPlane (void) const
Get the derived plane as transformed by its parent node.
void Ogre::MovablePlane::visitRenderables (Renderable::Visitor * visitor, bool debugRenderables = false) inline virtual
Method to allow a caller to abstractly iterate over the Renderable instances that this MovableObject will add to the render queue when asked, if any.
Parameters
visitor Pointer to a class implementing the Renderable::Visitor interface which will be called back for each Renderable which will be queued. Bear in mind that the state of the Renderable instances may not be finalised depending on when you call this.
debugRenderables If false, only regular renderables will be visited (those for normal display). If true, debug renderables will be included too.
Implements Ogre::MovableObject.
Side Ogre::Plane::getSide (const Vector3 & rkPoint) const inherited
Referenced by Ogre::PlaneBoundedVolume::intersects().
Side Ogre::Plane::getSide (const AxisAlignedBox & rkBox) const inherited
Returns the side where the alignedBox is.
The flag BOTH_SIDE indicates an intersecting box. One corner ON the plane is sufficient to consider the box and the plane intersecting.
Side Ogre::Plane::getSide (const Vector3 & centre, const Vector3 & halfSize) const inherited
Returns which side of the plane that the given box lies on.
The box is defined as centre/half-size pairs for effectively.
Parameters
centre The centre of the box.
halfSize The half-size of the box.
Returns
POSITIVE_SIDE if the box complete lies on the "positive side" of the plane, NEGATIVE_SIDE if the box complete lies on the "negative side" of the plane, and BOTH_SIDE if the box intersects the plane.
Real Ogre::Plane::getDistance (const Vector3 & rkPoint) const inherited
This is a pseudodistance.
The sign of the return value is positive if the point is on the positive side of the plane, negative if the point is on the negative side, and zero if the point is on the plane.
The absolute value of the return value is the true distance only when the plane normal is a unit length vector.
Referenced by Ogre::PlaneBoundedVolume::intersects().
void Ogre::Plane::redefine (const Vector3 & rkPoint0, const Vector3 & rkPoint1, const Vector3 & rkPoint2) inherited
Redefine this plane based on 3 points.
void Ogre::Plane::redefine (const Vector3 & rkNormal, const Vector3 & rkPoint) inherited
Redefine this plane based on a normal and a point.
Vector3 Ogre::Plane::projectVector (const Vector3 & v) const inherited
Project a vector onto the plane.
Remarks
This gives you the element of the input vector that is perpendicular to the normal of the plane. You can get the element which is parallel to the normal of the plane by subtracting the result of this method from the original vector, since parallel + perpendicular = original.
Parameters
v The input vector
Real Ogre::Plane::normalise (void) inherited
Normalises the plane.
Remarks
This method normalises the plane's normal and the length scale of d is as well.
Note
This function will not crash for zero-sized vectors, but there will be no changes made to their components.
Returns
The previous length of the plane's normal.
Plane Ogre::Plane::operator- () const inline inherited
Get flipped plane, with same location but reverted orientation.
References Ogre::Vector3::x, Ogre::Vector3::y, and Ogre::Vector3::z.
bool Ogre::Plane::operator== (const Plane & rhs) const inline inherited
Comparison operator.
References Ogre::Plane::d, and Ogre::Plane::normal.
bool Ogre::Plane::operator!= (const Plane & rhs) const inline inherited
References Ogre::Plane::d, Ogre::Plane::normal, and Ogre::operator<<().
virtual void Ogre::MovableObject::_notifyCreator (MovableObjectFactory * fact) inline virtual inherited
Notify the object of it's creator (internal use only)
MovableObjectFactory* Ogre::MovableObject::_getCreator (void) const inline inherited
Get the creator of this object, if any (internal use only)
virtual void Ogre::MovableObject::_notifyManager (SceneManager * man) inline virtual inherited
Notify the object of it's manager (internal use only)
SceneManager* Ogre::MovableObject::_getManager (void) const inline inherited
Get the manager of this object, if any (internal use only)
virtual void Ogre::MovableObject::_releaseManualHardwareResources () inline virtual inherited
Notifies the movable object that hardware resources were lost.
Remarks
Called automatically by RenderSystem if hardware resources were lost and can not be restored using some internal mechanism. Among affected resources are nested shadow renderables, ManualObjects, etc.
Reimplemented in Ogre::BillboardSet, Ogre::StaticGeometry::Region, Ogre::Entity, and Ogre::ManualObject.
virtual void Ogre::MovableObject::_restoreManualHardwareResources () inline virtual inherited
Notifies the movable object that hardware resources should be restored.
Remarks
Called automatically by RenderSystem if hardware resources were lost and can not be restored using some internal mechanism. Among affected resources are nested shadow renderables, ManualObjects, etc.
Reimplemented in Ogre::StaticGeometry::Region, and Ogre::Entity.
const String& Ogre::MovableObject::getName (void) const inline inherited
Returns the name of this object.
Node* Ogre::MovableObject::getParentNode (void) const inline inherited
Returns the node to which this object is attached.
Remarks
A MovableObject may be attached to either a SceneNode or to a TagPoint, the latter case if it's attached to a bone on an animated entity. Both are Node subclasses so this method will return either.
SceneNode* Ogre::MovableObject::getParentSceneNode (void) const inherited
Returns the scene node to which this object is attached.
Remarks
A MovableObject may be attached to either a SceneNode or to a TagPoint, the latter case if it's attached to a bone on an animated entity. This method will return the scene node of the parent entity if the latter is true.
bool Ogre::MovableObject::isParentTagPoint () const inline inherited
Gets whether the parent node is a TagPoint (or a SceneNode)
virtual void Ogre::MovableObject::_notifyAttached (Node * parent, bool isTagPoint = false) virtual inherited
Internal method called to notify the object that it has been attached to a node.
Reimplemented in Ogre::Entity, Ogre::ParticleSystem, Ogre::Light, Ogre::PortalBase, and Ogre::InstancedEntity.
Referenced by Ogre::PortalBase::_notifyAttached().
bool Ogre::MovableObject::isAttached (void) const inline inherited
Returns true if this object is attached to a SceneNode or TagPoint.
void Ogre::MovableObject::detachFromParent (void) inherited
Detaches an object from a parent SceneNode or TagPoint, if attached.
virtual bool Ogre::MovableObject::isInScene (void) const virtual inherited
Returns true if this object is attached to a SceneNode or TagPoint, and this SceneNode / TagPoint is currently in an active part of the scene graph.
Reimplemented in Ogre::InstancedEntity.
virtual void Ogre::MovableObject::_notifyMoved (void) virtual inherited
Internal method called to notify the object that it has been moved.
Reimplemented in Ogre::Light, Ogre::PortalBase, Ogre::InstancedEntity, and Ogre::PCZLight.
virtual const AxisAlignedBox& Ogre::MovableObject::getWorldBoundingBox (bool derive = false) const virtual inherited
Retrieves the axis-aligned bounding box for this object in world coordinates.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::Entity, and Ogre::PortalBase.
virtual const Sphere& Ogre::MovableObject::getWorldBoundingSphere (bool derive = false) const virtual inherited
Retrieves the worldspace bounding sphere for this object.
Reimplemented in Ogre::Entity, and Ogre::PortalBase.
void Ogre::MovableObject::setVisible (bool visible) inline inherited
Tells this object whether to be visible or not, if it has a renderable component.
Note
An alternative approach of making an object invisible is to detach it from it's SceneNode, or to remove the SceneNode entirely. Detaching a node means that structurally the scene graph changes. Once this change has taken place, the objects / nodes that have been removed have less overhead to the visibility detection pass than simply making the object invisible, so if you do this and leave the objects out of the tree for a long time, it's faster. However, the act of detaching / reattaching nodes is in itself more expensive than setting an object visibility flag, since in the latter case structural changes are not made. Therefore, small or frequent visibility changes are best done using this method; large or more longer term changes are best done by detaching.
Referenced by Ogre::Light::setVisible().
bool Ogre::MovableObject::getVisible (void) const inline inherited
Gets this object whether to be visible or not, if it has a renderable component.
Remarks
Returns the value set by MovableObject::setVisible only.
virtual bool Ogre::MovableObject::isVisible (void) const virtual inherited
Returns whether or not this object is supposed to be visible or not.
Remarks
Takes into account both upper rendering distance and visible flag.
Reimplemented in Ogre::InstancedGeometry::BatchInstance, and Ogre::StaticGeometry::Region.
Referenced by Ogre::Frustum::isCustomProjectionMatrixEnabled().
void Ogre::MovableObject::setRenderingDistance (Real dist) inline inherited
Sets the distance at which the object is no longer rendered.
Note
Camera::setUseRenderingDistance() needs to be called for this parameter to be used.
Parameters
dist Distance beyond which the object will not be rendered (the default is 0, which means objects are always rendered).
Real Ogre::MovableObject::getRenderingDistance (void) const inline inherited
Gets the distance at which batches are no longer rendered.
void Ogre::MovableObject::setRenderingMinPixelSize (Real pixelSize) inline inherited
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
Note
Camera::setUseMinPixelSize() needs to be called for this parameter to be used.
Parameters
pixelSize Number of minimum pixels (the default is 0, which means objects are always rendered).
Real Ogre::MovableObject::getRenderingMinPixelSize () const inline inherited
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
void Ogre::MovableObject::setUserAny (const Any & anything) inline inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this MovableObject. This can be a pointer back to one of your own classes for instance.
const Any& Ogre::MovableObject::getUserAny (void) const inline inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
UserObjectBindings& Ogre::MovableObject::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
const UserObjectBindings& Ogre::MovableObject::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
virtual void Ogre::MovableObject::setRenderQueueGroup (uint8 queueID) virtual inherited
Sets the render queue group this entity will be rendered through.
Remarks
Render queues are grouped to allow you to more tightly control the ordering of rendered objects. If you do not call this method, all Entity objects default to the default queue (RenderQueue::getDefaultQueueGroup), which is fine for most objects. You may want to alter this if you want this entity to always appear in front of other objects, e.g. for a 3D menu system or such.
See RenderQueue for more details.
Parameters
queueID Enumerated value of the queue group to use. See the enum RenderQueueGroupID for what kind of values can be used here.
Reimplemented in Ogre::ParticleSystem, and Ogre::Entity.
virtual void Ogre::MovableObject::setRenderQueueGroupAndPriority (uint8 queueID, ushort priority) virtual inherited
Sets the render queue group and group priority this entity will be rendered through.
Remarks
Render queues are grouped to allow you to more tightly control the ordering of rendered objects. Within a single render group there another type of grouping called priority which allows further control. If you do not call this method, all Entity objects default to the default queue and priority (RenderQueue::getDefaultQueueGroup, RenderQueue::getDefaultRenderablePriority), which is fine for most objects. You may want to alter this if you want this entity to always appear in front of other objects, e.g. for a 3D menu system or such.
See RenderQueue for more details.
Parameters
queueID Enumerated value of the queue group to use. See the enum RenderQueueGroupID for what kind of values can be used here.
priority The priority within a group to use.
Reimplemented in Ogre::ParticleSystem, and Ogre::Entity.
uint8 Ogre::MovableObject::getRenderQueueGroup (void) const inline inherited
Gets the queue group for this entity.
See also
setRenderQueueGroup
virtual const Matrix4& Ogre::MovableObject::_getParentNodeFullTransform (void) const virtual inherited
Return the full transformation of the parent sceneNode or the attachingPoint node.
Reimplemented in Ogre::InstancedEntity.
void Ogre::MovableObject::setQueryFlags (uint32 flags) inline inherited
Sets the query flags for this object.
Remarks
When performing a scene query, this object will be included or excluded according to flags on the object and flags on the query. This is a bitwise value, so only when a bit on these flags is set, will it be included in a query asking for that flag. The meaning of the bits is application-specific.
void Ogre::MovableObject::addQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
void Ogre::MovableObject::removeQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
uint32 Ogre::MovableObject::getQueryFlags (void) const inline inherited
Returns the query flags relevant for this object.
static void Ogre::MovableObject::setDefaultQueryFlags (uint32 flags) inline static inherited
Set the default query flags for all future MovableObject instances.
static uint32 Ogre::MovableObject::getDefaultQueryFlags () inline static inherited
Get the default query flags for all future MovableObject instances.
void Ogre::MovableObject::setVisibilityFlags (uint32 flags) inline inherited
Sets the visibility flags for this object.
Remarks
As well as a simple true/false value for visibility (as seen in setVisible), you can also set visibility flags which when 'and'ed with the SceneManager's visibility mask can also make an object invisible.
void Ogre::MovableObject::addVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
void Ogre::MovableObject::removeVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
uint32 Ogre::MovableObject::getVisibilityFlags (void) const inline inherited
Returns the visibility flags relevant for this object.
static void Ogre::MovableObject::setDefaultVisibilityFlags (uint32 flags) inline static inherited
Set the default visibility flags for all future MovableObject instances.
static uint32 Ogre::MovableObject::getDefaultVisibilityFlags () inline static inherited
Get the default visibility flags for all future MovableObject instances.
void Ogre::MovableObject::setListener (Listener * listener) inline inherited
Sets a listener for this object.
Remarks
Note for size and performance reasons only one listener per object is allowed.
Listener* Ogre::MovableObject::getListener (void) const inline inherited
Gets the current listener for this object.
const LightList& Ogre::MovableObject::queryLights (void) const inherited
Gets a list of lights, ordered relative to how close they are to this movable object.
Remarks
By default, this method gives the listener a chance to populate light list first, if there is no listener or Listener::objectQueryLights returns NULL, it'll query the light list from parent entity if it is present, or returns SceneNode::findLights if it has parent scene node, otherwise it just returns an empty list.
The object internally caches the light list, so it will recalculate it only when object is moved, or lights that affect the frustum have been changed (
See also
SceneManager::_getLightsDirtyCounter), but if listener exists, it will be called each time, so the listener should implement their own cache mechanism to optimise performance.
This method can be useful when implementing Renderable::getLights in case the renderable is a part of the movable.
Returns
The list of lights use to lighting this object.
uint32 Ogre::MovableObject::getLightMask () const inline inherited
Get a bitwise mask which will filter the lights affecting this object.
Remarks
By default, this mask is fully set meaning all lights will affect this object
void Ogre::MovableObject::setLightMask (uint32 lightMask) inherited
Set a bitwise mask which will filter the lights affecting this object.
Remarks
This mask will be compared against the mask held against Light to determine if a light should affect a given object. By default, this mask is fully set meaning all lights will affect this object
LightList* Ogre::MovableObject::_getLightList () inline inherited
Returns a pointer to the current list of lights for this object.
Remarks
You should not modify this list outside of MovableObject::Listener::objectQueryLights (say if you want to use it to implement this method, and use the pointer as a return value) and for reading it's only accurate as at the last frame.
EdgeData* Ogre::MovableObject::getEdgeList (void) inline virtual inherited
Returns details of the edges which might be used to determine a silhouette.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::StaticGeometry::Region.
bool Ogre::MovableObject::hasEdgeList (void) inline virtual inherited
Returns whether the object has a valid edge list.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::StaticGeometry::Region.
ShadowRenderableListIterator Ogre::MovableObject::getShadowVolumeRenderableIterator (ShadowTechnique shadowTechnique, const Light * light, HardwareIndexBufferSharedPtr * indexBuffer, size_t * indexBufferUsedSize, bool extrudeVertices, Real extrusionDist, unsigned long flags = 0) virtual inherited
Define a default implementation of method from ShadowCaster which implements no shadows.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::StaticGeometry::Region.
const AxisAlignedBox& Ogre::MovableObject::getLightCapBounds (void) const virtual inherited
Overridden member from ShadowCaster.
Implements Ogre::ShadowCaster.
const AxisAlignedBox& Ogre::MovableObject::getDarkCapBounds (const Light & light, Real dirLightExtrusionDist) const virtual inherited
Overridden member from ShadowCaster.
Implements Ogre::ShadowCaster.
void Ogre::MovableObject::setCastShadows (bool enabled) inline inherited
Sets whether or not this object will cast shadows.
Remarks
This setting simply allows you to turn on/off shadows for a given object. An object will not cast shadows unless the scene supports it in any case (see SceneManager::setShadowTechnique), and also the material which is in use must also have shadow casting enabled. By default all entities cast shadows. If, however, for some reason you wish to disable this for a single object then you can do so using this method.
Note
This method normally refers to objects which block the light, but since Light is also a subclass of MovableObject, in that context it means whether the light causes shadows itself.
bool Ogre::MovableObject::getCastShadows (void) const inline virtual inherited
Returns whether shadow casting is enabled for this object.
Implements Ogre::ShadowCaster.
bool Ogre::MovableObject::getReceivesShadows () inherited
Returns whether the Material of any Renderable that this MovableObject will add to the render queue will receive shadows.
Real Ogre::MovableObject::getPointExtrusionDistance (const Light * l) const virtual inherited
Get the distance to extrude for a point/spot light.
Implements Ogre::ShadowCaster.
virtual uint32 Ogre::MovableObject::getTypeFlags (void) const virtual inherited
Get the 'type flags' for this MovableObject.
Remarks
A type flag identifies the type of the MovableObject as a bitpattern. This is used for categorical inclusion / exclusion in SceneQuery objects. By default, this method returns all ones for objects not created by a MovableObjectFactory (hence always including them); otherwise it returns the value assigned to the MovableObjectFactory. Custom objects which don't use MovableObjectFactory will need to override this if they want to be included in queries.
Reimplemented in Ogre::BillboardSet, Ogre::Entity, Ogre::ParticleSystem, Ogre::Frustum, Ogre::StaticGeometry::Region, and Ogre::Light.
void Ogre::MovableObject::setDebugDisplayEnabled (bool enabled) inline inherited
Sets whether or not the debug display of this object is enabled.
Remarks
Some objects aren't visible themselves but it can be useful to display a debug representation of them. Or, objects may have an additional debug display on top of their regular display. This option enables / disables that debug display. Objects that are not visible never display debug geometry regardless of this setting.
bool Ogre::MovableObject::isDebugDisplayEnabled (void) const inline inherited
Gets whether debug display of this object is enabled.
static void Ogre::ShadowCaster::clearShadowRenderableList (ShadowRenderableList & shadowRenderables) static inherited
Common implementation of releasing shadow renderables.
static void Ogre::ShadowCaster::extrudeVertices (const HardwareVertexBufferSharedPtr & vertexBuffer, size_t originalVertexCount, const Vector4 & lightPos, Real extrudeDist) static inherited
Utility method for extruding vertices based on a light.
Remarks
Unfortunately, because D3D cannot handle homogeneous (4D) position coordinates in the fixed-function pipeline (GL can, but we have to be cross-API), when we extrude in software we cannot extrude to infinity the way we do in the vertex program (by setting w to 0.0f). Therefore we extrude by a fixed distance, which may cause some problems with larger scenes. Luckily better hardware (ie vertex programs) can fix this.
Parameters
vertexBuffer The vertex buffer containing ONLY xyz position values, which must be originalVertexCount * 2 * 3 floats long.
originalVertexCount The count of the original number of vertices, i.e. the number in the mesh, not counting the doubling which has already been done (by VertexData::prepareForShadowVolume) to provide the extruded area of the buffer.
lightPos 4D light position in object space, when w=0.0f this represents a directional light.
extrudeDist The distance to extrude.
const StringVector& Ogre::AnimableObject::getAnimableValueNames (void) const inline inherited
Gets a list of animable value names for this object.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
virtual AnimableValuePtr Ogre::AnimableObject::createAnimableValue (const String & valueName) inline virtual inherited
Create a reference-counted AnimableValuePtr for the named value.
Remarks
You can use the returned object to animate a value on this object, using AnimationTrack. Subclasses must override this if they wish to support animation of their values.
Reimplemented in Ogre::Light.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
Member Data Documentation
Vector3 Ogre::Plane::normal inherited
Referenced by Ogre::Plane::operator!=(), Ogre::Matrix4::operator*(), and Ogre::Plane::operator==().
Real Ogre::Plane::d inherited
Referenced by Ogre::Plane::operator!=(), Ogre::Matrix4::operator*(), and Ogre::Plane::operator==().
The documentation for this class was generated from the following file:
OgreMovablePlane.h