OGRE: HLMS
HLMS
Optional Components
High-level Material-System.
Classes
class Ogre::DefaultProperties
class Ogre::HlmsDatablock
class Ogre::HlmsManager
class Ogre::HlmsMaterialBase
class Ogre::PbsMaterial
struct Ogre::PbsMaterial::TextureAddressing
class Ogre::PropertyMap
struct Ogre::PropertyMap::Property
class Ogre::ShaderGenerator
class Ogre::ShaderManager
class Ogre::ShaderPiecesManager
class Ogre::ShaderTemplate
class Ogre::SubStringRef
Typedefs
typedef vector< std::pair< IdString, String > >::type Ogre::HlmsParamVec
Enumerations
enum Ogre::PbsMaterial::BlendFunction {
Ogre::PbsMaterial::BF_ALPHA = 0, Ogre::PbsMaterial::BF_ALPHA_PREMUL, Ogre::PbsMaterial::BF_ADD, Ogre::PbsMaterial::BF_SUBTRACT,
Ogre::PbsMaterial::BF_MULTIPLY, Ogre::PbsMaterial::BF_MULTIPLY_2X, Ogre::PbsMaterial::BF_SCREEN, Ogre::PbsMaterial::BF_OVERLAY,
Ogre::PbsMaterial::BF_LIGHTEN, Ogre::PbsMaterial::BF_DARKEN, Ogre::PbsMaterial::BF_GRAIN_EXTRACT, Ogre::PbsMaterial::BF_GRAIN_MERGE,
Ogre::PbsMaterial::BF_DIFFERENCE
}
enum Ogre::PbsMaterial::MapSlot { Ogre::PbsMaterial::MS_MAIN, Ogre::PbsMaterial::MS_D1, Ogre::PbsMaterial::MS_D2 }
Functions
Ogre::ShaderGenerator::Expression::Expression ()
Ogre::HlmsDatablock::HlmsDatablock (GpuProgramType type, PropertyMap *propertyMap)
Ogre::HlmsManager::HlmsManager (SceneManager *sceneManager, const String &pieseFilesResorceGroup=ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME)
Ogre::HlmsMaterialBase::HlmsMaterialBase ()
Ogre::PbsMaterial::PbsMaterial ()
Ogre::PbsMaterial::PbsMaterial (const PbsMaterial &obj)
Ogre::PropertyMap::Property::Property (IdString _keyName, int32 _value)
Ogre::PropertyMap::PropertyMap ()
Ogre::PbsMaterial::SamplerContainer::SamplerContainer ()
Ogre::ShaderManager::ShaderManager (SceneManager *sceneManager, const String &pieseFilesResorceGroup)
Ogre::ShaderPiecesManager::ShaderPiecesManager (const String &pieseFilesResorceGroup)
Ogre::ShaderTemplate::ShaderTemplate ()
Ogre::SubStringRef::SubStringRef (const String *original, size_t start)
Ogre::SubStringRef::SubStringRef (const String *original, size_t _start, size_t _end)
Ogre::SubStringRef::SubStringRef (const String *original, String::const_iterator _start)
Ogre::PbsMaterial::TextureAddressing::TextureAddressing ()
Ogre::PbsMaterial::TextureAddressing::TextureAddressing (TextureUnitState::TextureAddressingMode inU, TextureUnitState::TextureAddressingMode inV)
virtual Ogre::HlmsManager::~HlmsManager ()
virtual Ogre::HlmsMaterialBase::~HlmsMaterialBase ()
virtual Ogre::PbsMaterial::~PbsMaterial ()
virtual Ogre::PropertyMap::~PropertyMap ()
Ogre::ShaderManager::~ShaderManager ()
Ogre::ShaderPiecesManager::~ShaderPiecesManager ()
Ogre::ShaderTemplate::~ShaderTemplate ()
void Ogre::HlmsDatablock::addProfile (const String &profile)
String::const_iterator Ogre::SubStringRef::begin () const
void Ogre::HlmsManager::bind (Renderable *rend, HlmsMaterialBase *material, String passName)
uint32 Ogre::calcHash (const void *data, size_t size)
uint32 Ogre::calcHash (String str)
uint32 Ogre::calcHash (const StringVector &vec)
static GpuProgramPtr Ogre::ShaderManager::createGpuProgram (const String &name, const String &code, HlmsDatablock *dataBlock)
virtual void Ogre::HlmsMaterialBase::createTextureUnits (Pass *pass)
this is called once per frame if the shader has changed. (it is guaranteed that there are not texture units in the pass)
void Ogre::PbsMaterial::createTextureUnits (Pass *pass)
this is called once per frame if the shader has changed. (it is guaranteed that there are not texture units in the pass)
String::const_iterator Ogre::SubStringRef::end () const
void Ogre::ShaderPiecesManager::enumeratePieceFiles ()
size_t Ogre::SubStringRef::find (const char *value, size_t pos=0) const
size_t Ogre::SubStringRef::find (const String &value) const
size_t Ogre::SubStringRef::findFirstOf (const char *c, size_t pos) const
ColourValue Ogre::PbsMaterial::getAlbedo ()
size_t Ogre::SubStringRef::getEnd (void) const
ColourValue Ogre::PbsMaterial::getF0 ()
HlmsDatablock * Ogre::HlmsMaterialBase::getFragmentDatablock ()
GpuProgramPtr Ogre::ShaderManager::getGpuProgram (HlmsDatablock *dataBlock)
uint32 Ogre::ShaderTemplate::getHash ()
uint32 Ogre::HlmsDatablock::getHash ()
uint32 Ogre::PropertyMap::getHash ()
const String & Ogre::HlmsDatablock::getLanguage ()
Real Ogre::PbsMaterial::getLightRoughnessOffset ()
const String & Ogre::SubStringRef::getOriginalBuffer () const
const StringVector & Ogre::ShaderPiecesManager::getPieces (const String &language, GpuProgramType shaderType, bool reload=false)
const StringVector & Ogre::HlmsDatablock::getProfileList ()
int32 Ogre::PropertyMap::getProperty (IdString key, int32 defaultVal=0)
PropertyMap * Ogre::HlmsDatablock::getPropertyMap ()
PropertyMap & Ogre::HlmsMaterialBase::getPropertyMap ()
Real Ogre::PbsMaterial::getRoughness ()
GpuProgramType Ogre::HlmsDatablock::getShaderType ()
size_t Ogre::SubStringRef::getSize (void) const
size_t Ogre::SubStringRef::getStart (void) const
const String & Ogre::ShaderTemplate::getTemplate ()
ShaderTemplate * Ogre::HlmsDatablock::getTemplate ()
const String & Ogre::ShaderTemplate::getTemplateFileName ()
HlmsDatablock * Ogre::HlmsMaterialBase::getVertexDatablock ()
bool Ogre::HlmsManager::hasBinding (Renderable *rend, String passName)
bool Ogre::PropertyMap::hasProperty (IdString key)
void Ogre::PbsMaterial::SamplerContainer::init (String n, bool hasBlendFu=false, bool hasBlendFc1=false, bool hasBlendFc2=false, bool needsGammaCorrect=false, bool hasIntens=false, bool hasMipmapC=false, TextureType texType=TEX_TYPE_2D)
void Ogre::ShaderTemplate::load ()
bool Ogre::SubStringRef::matchEqual (const char *stringCompare) const
virtual void Ogre::HlmsManager::notifyRenderSingleObject (Renderable *rend, const Pass *pass, const AutoParamDataSource *source, const LightList *pLightList, bool suppressRenderStateChanges)
Event raised when render single object started.
bool Ogre::PropertyMap::Property::operator== (const Property &_r) const
bool Ogre::PbsMaterial::TextureAddressing::operator== (const TextureAddressing &b)
bool Ogre::OrderParamVecByKey (const std::pair< IdString, String > &_left, const std::pair< IdString, String > &_right)
static String Ogre::ShaderGenerator::parse (String &inBuffer, PropertyMap &properties, const StringVector &pieceFiles)
virtual void Ogre::HlmsManager::preFindVisibleObjects (SceneManager *source, SceneManager::IlluminationRenderStage irs, Viewport *v)
Called prior to searching for visible objects in this SceneManager.
void Ogre::PropertyMap::removeProperty (IdString key)
void Ogre::PbsMaterial::setAlbedo (ColourValue val)
void Ogre::PbsMaterial::setAlbedoTexture (MapSlot mapSlot, TexturePtr tex, TextureAddressing textureAddressing=TextureAddressing(), BlendFunction blendFunc=BF_ALPHA, float blendFactor=0)
void Ogre::PropertyMap::setCommonProperties ()
Inserts common properties about the current Renderable, such as hlms_skeleton hlms_uv_count, etc.
void Ogre::SubStringRef::setEnd (size_t newEnd)
void Ogre::PbsMaterial::setEnvironmentMap (TexturePtr tex, float intensityFactor=1.0f)
void Ogre::PbsMaterial::setF0 (ColourValue val)
void Ogre::PbsMaterial::setF0Texture (MapSlot mapSlot, TexturePtr tex, TextureAddressing textureAddressing=TextureAddressing(), BlendFunction blendFunc=BF_ALPHA, float blendFactor=0)
void Ogre::HlmsDatablock::setLanguage (const String &language)
void Ogre::PbsMaterial::setLightRoughnessOffset (Real val)
void Ogre::PbsMaterial::setNormalRTexture (MapSlot mapSlot, TexturePtr tex, TextureAddressing textureAddressing=TextureAddressing(), float normalBlendFactor=0, float rBlendFactor=0)
set texture containing normals and roughness
void Ogre::PbsMaterial::setOffsetAndScale (MapSlot mapSlot, Vector2 offset, Vector2 scale)
void Ogre::PropertyMap::setProperty (IdString key, int32 value)
void Ogre::PbsMaterial::setRoughness (Real val)
void Ogre::SubStringRef::setStart (size_t newStart)
void Ogre::ShaderTemplate::setTemplateFileName (const String &templateFileName)
void Ogre::HlmsDatablock::setTemplateName (const String &tamplateName)
void Ogre::PbsMaterial::setUvSetIndex (MapSlot mapSlot, uint index)
void Ogre::HlmsManager::unbind (Renderable *rend, String passName)
void Ogre::HlmsManager::unbindAll (String passName)
virtual void Ogre::HlmsMaterialBase::updatePropertyMap (Camera *camera, const LightList *pLightList)
this is called once per frame
void Ogre::PbsMaterial::updatePropertyMap (Camera *camera, const LightList *pLightList)
this is called once per frame
void Ogre::PbsMaterial::updateTextureUnits (TextureUnitState *textureUnitState, GpuProgramParametersSharedPtr fragmentParams, SamplerContainer &s, int index)
virtual void Ogre::HlmsMaterialBase::updateUniforms (const Pass *pass, const AutoParamDataSource *source, const LightList *pLightList)
this is called for every renderable before it is renderd with the given pass
void Ogre::PbsMaterial::updateUniforms (const Pass *pass, const AutoParamDataSource *source, const LightList *pLightList)
this is called for every renderable before it is renderd with the given pass
Variables
static const IdString Ogre::DefaultProperties::AlphaTest
float Ogre::PbsMaterial::SamplerContainer::blendFactor1
float Ogre::PbsMaterial::SamplerContainer::blendFactor2
BlendFunction Ogre::PbsMaterial::SamplerContainer::blendFunc
static const IdString Ogre::DefaultProperties::BonesPerVertex
vector< Expression >::type Ogre::ShaderGenerator::Expression::children
static const IdString Ogre::DefaultProperties::Colour
static const IdString Ogre::DefaultProperties::DualParaboloidMapping
const String Ogre::FilePatterns [] = { "_vs", "_fs", "_gs", "_ds", "_hs" }
static const IdString Ogre::DefaultProperties::GL3Plus
bool Ogre::PbsMaterial::SamplerContainer::hasBlendFactor1
bool Ogre::PbsMaterial::SamplerContainer::hasBlendFactor2
bool Ogre::PbsMaterial::SamplerContainer::hasBlendFunc
bool Ogre::PbsMaterial::SamplerContainer::hasIntensity
bool Ogre::PbsMaterial::SamplerContainer::hasMipmapCount
static const IdString Ogre::DefaultProperties::HighQuality
float Ogre::PbsMaterial::SamplerContainer::intensity
bool Ogre::HlmsMaterialBase::IsDirty
IdString Ogre::PropertyMap::Property::keyName
static const IdString Ogre::DefaultProperties::LightsAttenuation
static const IdString Ogre::DefaultProperties::LightsDirectional
static const IdString Ogre::DefaultProperties::LightsPoint
static const IdString Ogre::DefaultProperties::LightsSpot
static const IdString Ogre::DefaultProperties::LightsSpotParams
float Ogre::PbsMaterial::SamplerContainer::mipmapCount
String Ogre::PbsMaterial::SamplerContainer::name
bool Ogre::PbsMaterial::SamplerContainer::needsGammaCorrection
bool Ogre::ShaderGenerator::Expression::negated
static const IdString Ogre::DefaultProperties::Normal
static const IdString Ogre::DefaultProperties::NumShadowMaps
static const IdString Ogre::DefaultProperties::Pose
static const IdString Ogre::DefaultProperties::PssmSplits
static const IdString Ogre::DefaultProperties::QTangent
bool Ogre::ShaderGenerator::Expression::result
static const IdString Ogre::DefaultProperties::ShadowCaster
static const IdString Ogre::DefaultProperties::Skeleton
These are "default" or "Base" properties common to many implementations and thus defined here.
SamplerStatus Ogre::PbsMaterial::SamplerContainer::status
static const IdString Ogre::DefaultProperties::Tangent
TexturePtr Ogre::PbsMaterial::SamplerContainer::tex
TextureAddressing Ogre::PbsMaterial::SamplerContainer::textureAddressing
TextureType Ogre::PbsMaterial::SamplerContainer::textureType
TextureUnitState * Ogre::PbsMaterial::SamplerContainer::textureUnitState
ExpressionType Ogre::ShaderGenerator::Expression::type
TextureUnitState::TextureAddressingMode Ogre::PbsMaterial::TextureAddressing::u
static const IdString Ogre::DefaultProperties::UvCount
static const IdString Ogre::DefaultProperties::UvCount0
static const IdString Ogre::DefaultProperties::UvCount1
static const IdString Ogre::DefaultProperties::UvCount2
static const IdString Ogre::DefaultProperties::UvCount3
static const IdString Ogre::DefaultProperties::UvCount4
static const IdString Ogre::DefaultProperties::UvCount5
static const IdString Ogre::DefaultProperties::UvCount6
static const IdString Ogre::DefaultProperties::UvCount7
static const IdString * Ogre::DefaultProperties::UvCountPtrs [8]
TextureUnitState::TextureAddressingMode Ogre::PbsMaterial::TextureAddressing::v
int32 Ogre::PropertyMap::Property::value
String Ogre::ShaderGenerator::Expression::value
Detailed Description
High-level Material-System.
Typedef Documentation
typedef vector< std::pair<IdString, String> >::type Ogre::HlmsParamVec
Enumeration Type Documentation
enum Ogre::PbsMaterial::BlendFunction
Enumerator
BF_ALPHA
BF_ALPHA_PREMUL
BF_ADD
BF_SUBTRACT
BF_MULTIPLY
BF_MULTIPLY_2X
BF_SCREEN
BF_OVERLAY
BF_LIGHTEN
BF_DARKEN
BF_GRAIN_EXTRACT
BF_GRAIN_MERGE
BF_DIFFERENCE
enum Ogre::PbsMaterial::MapSlot
Enumerator
MS_MAIN
MS_D1
MS_D2
Function Documentation
Ogre::HlmsDatablock::HlmsDatablock (GpuProgramType type, PropertyMap * propertyMap)
PropertyMap* Ogre::HlmsDatablock::getPropertyMap () inline
GpuProgramType Ogre::HlmsDatablock::getShaderType () inline
const String& Ogre::HlmsDatablock::getLanguage (void) inline
ShaderTemplate* Ogre::HlmsDatablock::getTemplate ()
const StringVector& Ogre::HlmsDatablock::getProfileList () inline
void Ogre::HlmsDatablock::setLanguage (const String & language)
void Ogre::HlmsDatablock::setTemplateName (const String & tamplateName)
void Ogre::HlmsDatablock::addProfile (const String & profile)
uint32 Ogre::HlmsDatablock::getHash ()
Ogre::HlmsManager::HlmsManager (SceneManager * sceneManager, const String & pieseFilesResorceGroup = ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME)
virtual Ogre::HlmsManager::~HlmsManager () virtual
virtual void Ogre::HlmsManager::notifyRenderSingleObject (Renderable * rend, const Pass * pass, const AutoParamDataSource * source, const LightList * pLightList, bool suppressRenderStateChanges) virtual
Event raised when render single object started.
Remarks
This method is called by the SceneManager.
Parameters
rend The renderable that is going to be rendered.
pass The pass which was set.
source The auto parameter source used within this render call.
pLightList The light list in use.
suppressRenderStateChanges True if render state changes should be suppressed.
Implements Ogre::RenderObjectListener.
virtual void Ogre::HlmsManager::preFindVisibleObjects (SceneManager * source, SceneManager::IlluminationRenderStage irs, Viewport * v) virtual
Called prior to searching for visible objects in this SceneManager.
Remarks
Note that the render queue at this stage will be full of the last render's contents and will be cleared after this method is called.
Parameters
source The SceneManager instance raising this event.
irs The stage of illumination being dealt with. IRS_NONE for a regular render, IRS_RENDER_TO_TEXTURE for a shadow caster render.
v The viewport being updated. You can get the camera from here.
Reimplemented from Ogre::SceneManager::Listener.
void Ogre::HlmsManager::bind (Renderable * rend, HlmsMaterialBase * material, String passName)
void Ogre::HlmsManager::unbind (Renderable * rend, String passName)
void Ogre::HlmsManager::unbindAll (String passName)
bool Ogre::HlmsManager::hasBinding (Renderable * rend, String passName)
Ogre::HlmsMaterialBase::HlmsMaterialBase ()
virtual Ogre::HlmsMaterialBase::~HlmsMaterialBase () virtual
HlmsDatablock* Ogre::HlmsMaterialBase::getVertexDatablock () inline
HlmsDatablock* Ogre::HlmsMaterialBase::getFragmentDatablock () inline
PropertyMap& Ogre::HlmsMaterialBase::getPropertyMap () inline
virtual void Ogre::HlmsMaterialBase::updatePropertyMap (Camera * camera, const LightList * pLightList) inline virtual
this is called once per frame
Reimplemented in Ogre::PbsMaterial.
virtual void Ogre::HlmsMaterialBase::createTextureUnits (Pass * pass) inline virtual
this is called once per frame if the shader has changed. (it is guaranteed that there are not texture units in the pass)
Reimplemented in Ogre::PbsMaterial.
virtual void Ogre::HlmsMaterialBase::updateUniforms (const Pass * pass, const AutoParamDataSource * source, const LightList * pLightList) inline virtual
this is called for every renderable before it is renderd with the given pass
Reimplemented in Ogre::PbsMaterial.
Ogre::PbsMaterial::TextureAddressing::TextureAddressing () inline
Ogre::PbsMaterial::TextureAddressing::TextureAddressing (TextureUnitState::TextureAddressingMode inU, TextureUnitState::TextureAddressingMode inV) inline
bool Ogre::PbsMaterial::TextureAddressing::operator== (const TextureAddressing & b) inline
References Ogre::PbsMaterial::TextureAddressing::u, and Ogre::PbsMaterial::TextureAddressing::v.
Ogre::PbsMaterial::SamplerContainer::SamplerContainer () inline
void Ogre::PbsMaterial::SamplerContainer::init (String n, bool hasBlendFu = false, bool hasBlendFc1 = false, bool hasBlendFc2 = false, bool needsGammaCorrect = false, bool hasIntens = false, bool hasMipmapC = false, TextureType texType = TEX_TYPE_2D) inline
Ogre::PbsMaterial::PbsMaterial ()
Ogre::PbsMaterial::PbsMaterial (const PbsMaterial & obj)
virtual Ogre::PbsMaterial::~PbsMaterial () virtual
void Ogre::PbsMaterial::setEnvironmentMap (TexturePtr tex, float intensityFactor = 1.0f)
ColourValue Ogre::PbsMaterial::getAlbedo () inline
void Ogre::PbsMaterial::setAlbedo (ColourValue val) inline
ColourValue Ogre::PbsMaterial::getF0 () inline
void Ogre::PbsMaterial::setF0 (ColourValue val) inline
Real Ogre::PbsMaterial::getRoughness () inline
void Ogre::PbsMaterial::setRoughness (Real val) inline
Real Ogre::PbsMaterial::getLightRoughnessOffset () inline
void Ogre::PbsMaterial::setLightRoughnessOffset (Real val) inline
References PBS_MAX_LIGHT_COUNT.
void Ogre::PbsMaterial::setAlbedoTexture (MapSlot mapSlot, TexturePtr tex, TextureAddressing textureAddressing = TextureAddressing(), BlendFunction blendFunc = BF_ALPHA, float blendFactor = 0)
void Ogre::PbsMaterial::setNormalRTexture (MapSlot mapSlot, TexturePtr tex, TextureAddressing textureAddressing = TextureAddressing(), float normalBlendFactor = 0, float rBlendFactor = 0)
set texture containing normals and roughness
void Ogre::PbsMaterial::setF0Texture (MapSlot mapSlot, TexturePtr tex, TextureAddressing textureAddressing = TextureAddressing(), BlendFunction blendFunc = BF_ALPHA, float blendFactor = 0)
void Ogre::PbsMaterial::setOffsetAndScale (MapSlot mapSlot, Vector2 offset, Vector2 scale)
void Ogre::PbsMaterial::setUvSetIndex (MapSlot mapSlot, uint index)
void Ogre::PbsMaterial::updatePropertyMap (Camera * camera, const LightList * pLightList) virtual
this is called once per frame
Reimplemented from Ogre::HlmsMaterialBase.
void Ogre::PbsMaterial::createTextureUnits (Pass * pass) virtual
this is called once per frame if the shader has changed. (it is guaranteed that there are not texture units in the pass)
Reimplemented from Ogre::HlmsMaterialBase.
void Ogre::PbsMaterial::updateUniforms (const Pass * pass, const AutoParamDataSource * source, const LightList * pLightList) virtual
this is called for every renderable before it is renderd with the given pass
Reimplemented from Ogre::HlmsMaterialBase.
void Ogre::PbsMaterial::updateTextureUnits (TextureUnitState * textureUnitState, GpuProgramParametersSharedPtr fragmentParams, SamplerContainer & s, int index)
Ogre::PropertyMap::Property::Property (IdString _keyName, int32 _value) inline
bool Ogre::PropertyMap::Property::operator== (const Property & _r) const inline
References Ogre::PropertyMap::Property::keyName, and Ogre::PropertyMap::Property::value.
Ogre::PropertyMap::PropertyMap ()
virtual Ogre::PropertyMap::~PropertyMap () virtual
void Ogre::PropertyMap::setCommonProperties ()
Inserts common properties about the current Renderable, such as hlms_skeleton hlms_uv_count, etc.
void Ogre::PropertyMap::setProperty (IdString key, int32 value)
bool Ogre::PropertyMap::hasProperty (IdString key)
int32 Ogre::PropertyMap::getProperty (IdString key, int32 defaultVal = 0)
void Ogre::PropertyMap::removeProperty (IdString key)
uint32 Ogre::PropertyMap::getHash ()
Ogre::SubStringRef::SubStringRef (const String * original, size_t start) inline
Ogre::SubStringRef::SubStringRef (const String * original, size_t _start, size_t _end) inline
Ogre::SubStringRef::SubStringRef (const String * original, String::const_iterator _start) inline
size_t Ogre::SubStringRef::find (const char * value, size_t pos = 0) const inline
size_t Ogre::SubStringRef::find (const String & value) const inline
size_t Ogre::SubStringRef::findFirstOf (const char * c, size_t pos) const inline
bool Ogre::SubStringRef::matchEqual (const char * stringCompare) const inline
void Ogre::SubStringRef::setStart (size_t newStart) inline
void Ogre::SubStringRef::setEnd (size_t newEnd) inline
size_t Ogre::SubStringRef::getStart (void) const inline
size_t Ogre::SubStringRef::getEnd (void) const inline
size_t Ogre::SubStringRef::getSize (void) const inline
String::const_iterator Ogre::SubStringRef::begin () const inline
String::const_iterator Ogre::SubStringRef::end (void) const inline
const String& Ogre::SubStringRef::getOriginalBuffer () const inline
bool Ogre::OrderParamVecByKey (const std::pair< IdString, String > & _left, const std::pair< IdString, String > & _right) inline
uint32 Ogre::calcHash (const void * data, size_t size) inline
References Ogre::MurmurHash3_x86_32(), and Ogre::IdString::Seed.
Referenced by Ogre::calcHash().
uint32 Ogre::calcHash (String str) inline
References Ogre::calcHash().
uint32 Ogre::calcHash (const StringVector & vec) inline
References Ogre::calcHash().
Ogre::ShaderGenerator::Expression::Expression () inline
static String Ogre::ShaderGenerator::parse (String & inBuffer, PropertyMap & properties, const StringVector & pieceFiles) static
Ogre::ShaderManager::ShaderManager (SceneManager * sceneManager, const String & pieseFilesResorceGroup)
Ogre::ShaderManager::~ShaderManager ()
GpuProgramPtr Ogre::ShaderManager::getGpuProgram (HlmsDatablock * dataBlock)
static GpuProgramPtr Ogre::ShaderManager::createGpuProgram (const String & name, const String & code, HlmsDatablock * dataBlock) static
Ogre::ShaderPiecesManager::ShaderPiecesManager (const String & pieseFilesResorceGroup)
Ogre::ShaderPiecesManager::~ShaderPiecesManager ()
void Ogre::ShaderPiecesManager::enumeratePieceFiles ()
const StringVector& Ogre::ShaderPiecesManager::getPieces (const String & language, GpuProgramType shaderType, bool reload = false)
Ogre::ShaderTemplate::ShaderTemplate ()
Ogre::ShaderTemplate::~ShaderTemplate ()
const String& Ogre::ShaderTemplate::getTemplateFileName () inline
void Ogre::ShaderTemplate::setTemplateFileName (const String & templateFileName)
void Ogre::ShaderTemplate::load ()
const String& Ogre::ShaderTemplate::getTemplate ()
uint32 Ogre::ShaderTemplate::getHash ()
Variable Documentation
bool Ogre::HlmsMaterialBase::IsDirty
TextureUnitState::TextureAddressingMode Ogre::PbsMaterial::TextureAddressing::u
Referenced by Ogre::PbsMaterial::TextureAddressing::operator==().
TextureUnitState::TextureAddressingMode Ogre::PbsMaterial::TextureAddressing::v
Referenced by Ogre::PbsMaterial::TextureAddressing::operator==().
String Ogre::PbsMaterial::SamplerContainer::name
TextureType Ogre::PbsMaterial::SamplerContainer::textureType
TexturePtr Ogre::PbsMaterial::SamplerContainer::tex
TextureUnitState* Ogre::PbsMaterial::SamplerContainer::textureUnitState
SamplerStatus Ogre::PbsMaterial::SamplerContainer::status
bool Ogre::PbsMaterial::SamplerContainer::hasIntensity
float Ogre::PbsMaterial::SamplerContainer::intensity
bool Ogre::PbsMaterial::SamplerContainer::hasMipmapCount
float Ogre::PbsMaterial::SamplerContainer::mipmapCount
bool Ogre::PbsMaterial::SamplerContainer::hasBlendFunc
BlendFunction Ogre::PbsMaterial::SamplerContainer::blendFunc
bool Ogre::PbsMaterial::SamplerContainer::hasBlendFactor1
float Ogre::PbsMaterial::SamplerContainer::blendFactor1
bool Ogre::PbsMaterial::SamplerContainer::hasBlendFactor2
float Ogre::PbsMaterial::SamplerContainer::blendFactor2
TextureAddressing Ogre::PbsMaterial::SamplerContainer::textureAddressing
bool Ogre::PbsMaterial::SamplerContainer::needsGammaCorrection
const IdString Ogre::DefaultProperties::Skeleton static
These are "default" or "Base" properties common to many implementations and thus defined here.
const IdString Ogre::DefaultProperties::BonesPerVertex static
const IdString Ogre::DefaultProperties::Pose static
const IdString Ogre::DefaultProperties::Normal static
const IdString Ogre::DefaultProperties::QTangent static
const IdString Ogre::DefaultProperties::Tangent static
const IdString Ogre::DefaultProperties::Colour static
const IdString Ogre::DefaultProperties::UvCount static
const IdString Ogre::DefaultProperties::UvCount0 static
const IdString Ogre::DefaultProperties::UvCount1 static
const IdString Ogre::DefaultProperties::UvCount2 static
const IdString Ogre::DefaultProperties::UvCount3 static
const IdString Ogre::DefaultProperties::UvCount4 static
const IdString Ogre::DefaultProperties::UvCount5 static
const IdString Ogre::DefaultProperties::UvCount6 static
const IdString Ogre::DefaultProperties::UvCount7 static
const IdString Ogre::DefaultProperties::LightsDirectional static
const IdString Ogre::DefaultProperties::LightsPoint static
const IdString Ogre::DefaultProperties::LightsSpot static
const IdString Ogre::DefaultProperties::LightsAttenuation static
const IdString Ogre::DefaultProperties::LightsSpotParams static
const IdString Ogre::DefaultProperties::DualParaboloidMapping static
const IdString Ogre::DefaultProperties::NumShadowMaps static
const IdString Ogre::DefaultProperties::PssmSplits static
const IdString Ogre::DefaultProperties::ShadowCaster static
const IdString Ogre::DefaultProperties::AlphaTest static
const IdString Ogre::DefaultProperties::GL3Plus static
const IdString Ogre::DefaultProperties::HighQuality static
const IdString* Ogre::DefaultProperties::UvCountPtrs[8] static
IdString Ogre::PropertyMap::Property::keyName
Referenced by Ogre::PropertyMap::Property::operator==().
int32 Ogre::PropertyMap::Property::value
Referenced by Ogre::PropertyMap::Property::operator==().
const String Ogre::FilePatterns[] = { "_vs", "_fs", "_gs", "_ds", "_hs" }
bool Ogre::ShaderGenerator::Expression::result
bool Ogre::ShaderGenerator::Expression::negated
ExpressionType Ogre::ShaderGenerator::Expression::type
vector<Expression>::type Ogre::ShaderGenerator::Expression::children
String Ogre::ShaderGenerator::Expression::value